import { CSS, EARLY_THEME_JS } from "../report/html/assets.js";
import { safeJson } from "../report/html/render.js";
import { UI_LIB } from "../report/html/ui.js";
import type { MatrixReport } from "./matrix.js";

const escapeHtml = (s: string): string => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

/** The matrix page, reading the embedded data (no network, no links out: runs live in your database). */
const MATRIX_APP = String.raw`
(function () {
  'use strict';
  var U = RegradeUI, h = U.h;
  var D;
  try { D = JSON.parse(document.getElementById('regrade-data').textContent); } catch (e) { return; }
  var M = D.matrix;
  var app = document.getElementById('app');
  var header = h('header', { class: 'top' },
    h('div', null,
      h('div', { class: 'brand', text: 'Regrade matrix' }),
      h('h1', { text: M.suiteName }),
      h('p', { class: 'meta', text: M.variants.length + ' variants  ·  matrix ' + M.matrixId.slice(0, 8) + '  ·  ' + U.when(M.startedAt) + '  ·  compared with ' + M.reference })),
    U.themeButton());
  var footer = h('footer', { text: 'Generated by Regrade ' + D.version + ' on ' + U.when(D.generatedAt) + '. A single self-contained file: it loads nothing from the network. Each variant is a run in your results database: regrade show <run>.' });
  app.textContent = '';
  app.appendChild(h('div', { class: 'wrap' }, header, U.matrixView(M), footer));
})();
`;

/** One self-contained HTML file for a matrix, like the run report. */
export function renderMatrixHtml(m: MatrixReport, version: string, generatedAt = new Date().toISOString()): string {
  const title = `Regrade matrix · ${m.suiteName}`;
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="light dark">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src data:">
<title>${escapeHtml(title)}</title>
<script>${EARLY_THEME_JS}</script>
<style>${CSS}</style>
</head>
<body>
<div id="app"><div class="wrap"><h1>${escapeHtml(m.suiteName)}</h1><p class="meta">Regrade matrix · ${m.variants.length} variants</p><noscript><p class="meta">This report needs JavaScript. The complete data is embedded in this file.</p></noscript></div></div>
<script type="application/json" id="regrade-data">${safeJson({ version, generatedAt, matrix: m })}</script>
<script>${UI_LIB}${MATRIX_APP}</script>
</body>
</html>
`;
}

export { MATRIX_APP };
